### ISSUE TITLE
Is it possible to create a PCL of this library?

### ISSUE THREAD

**Issue by fubar-coder** [Ruzzie/flashcache#1]
It'd be nice if there would be a PCL version of this library supporting .NET 4.5, .NET Core 5, Win8, WP 8.1, Win Phone Silverlight 8.

**Comment by Ruzzie** [comment]
I didn't create a PCL initially because of the thread synchronization limitations of PCL (and because I didn't need it yet) But I will take a look!

**Comment by Ruzzie** [comment]
I added a PCL version for: Portable-net45+sl50+netcore45+wpa81+wp8. I will wait a bit for .NET Core 5 until it is out of beta.

**Comment by fubar-coder** [comment]
.NET Core is now available as RC1, but I understand when you want to wait until the release :grinning:
